### ISSUE TITLE
test_delete_a_repository failure

### ISSUE THREAD

**Issue by jayvdb** [babygame0ver/gitpy#12]
```
> token=... username=jayvdb coverage run -m unittest discover
......E..
======================================================================
ERROR: test_delete_a_repository (tests.test_repos.TestRepository)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/path/to/gitpy/tests/test_repos.py", line 136, in test_delete_a_repository
    if (response[1] == 204):
IndexError: string index out of range

----------------------------------------------------------------------
Ran 9 tests in 23.355s

FAILED (errors=1)
```

I am using requests 2.22.0

`response` is an empty string, which isnt too helpful, and looks like the test logic is questionable..?

I guess I didnt give my token enough rights..?

Also would be a good idea to update the readme to indicate that token/username envvars are needed to run the tests, and the scopes that the token needs.

**Comment by babygame0ver** [comment]
Hello @jayvdb 

I have mentioned in the dependencies  in config.md. You can check it here.  https://github.com/babygame0ver/gitpy/blob/master/config.md

To obtain Access token from GitHub I have also given the link to github docs.

If you think any key information is missing before running the program, I will update the docs as per your feedback.
